class Neuron:
    def __init__(self, text):
        self.text = text        
        self.next_is_noun = False
        self.next_is_verb = False
        self.next_is_noun_or_verb = False        
        self.past_tense = False
        self.future_tense = False
        self.present_tense = False
        self.continuous = False
        self.is_verb = False
        self.is_noun = False
        self.place = False
        self.location = False
        self.owned_by = False
        self.character = False
        self.mode = False
        self.frequency = False
        self.person = False
        self.time = False
        self.action = False
        self.root_verb = None
        self.conn_nouns = []
